language: python
fast_finish: true

if: tag IS blank

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7
      env: CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    - os: osx
      language: generic

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        # use a virtual environment to avoid having to do "pip3 install --user"
        python3 -m venv venv
        source venv/bin/activate
    fi
  - pip install -e . --upgrade --upgrade-strategy eager

script:
  - bash tests.sh
  - python3 tsd/test_search_scihub.py
  - python3 tsd/test_search_stac.py
